### ISSUE TITLE
Hearder is seen transperently with the website page when we scroll up.

### ISSUE THREAD

**Issue by IswarPatro** [INCF/niQC#59] opened 2023-02-28 12:21 UTC
In the website https://incf.github.io/niQC/ when we scroll down and up i can see there is a transperently merging of header with website home page.

**Comment by IswarPatro** [comment] 2023-02-28 12:22
I want to work on this issue please assign me this issue.

**Comment by raamana** [comment] 2023-02-28 14:19
thansk @IswarPatro - it would be great to take your help. how would you fix it? make it less transparent?

**Comment by Inzamamdev** [comment] 2023-03-10 05:54
Can make the navbar as sticky navbar

**Comment by IswarPatro** [comment] 2023-04-22 08:45
Thanks @raamana for your response.I am participating in GSoC 2023 for that reason i am not able to check my past issue raise.I make navbar sticky .Also navbar have some design and css changes if you assign me this i will fix this issues.

**Comment by Amanyadav207** [comment] 2023-11-14 05:49
As the issue is still open, Please let me know the status of the issue. If the issue is still open, I am eager to work on this is issue. I have experience in HTML,CSS,Python and Java.Please assign the issue to me.

**Comment by raamana** [comment] 2023-11-14 14:23
it is still open!

**Comment by Amanyadav207** [comment] 2023-11-15 15:53
Hi @raamana what is the expected behavior we want this issue.
I have multiple thoughts like:
1. we can make the header sticky
2. remove the transparency effect completely
3.  or we can disable the header appearance effect while scrolling up on the website.

Please let me know I will open the PR accordingly

**Comment by Amanyadav207** [comment] 2023-11-22 13:16
hi @raamana could you please reply to the above comment . I am still interested in this

**Comment by raamana** [comment] 2023-11-22 15:05
Sure, go ahead with your suggestion!

**Comment by Amanyadav207** [comment] 2023-11-22 16:20
hi @raamana can please tell what have to be done out these .So that i can open PR accordingly
> * we can make the header sticky
> * remove the transparency effect completely
> * or we can disable the header appearance effect while scrolling up on the website.

**Comment by raamana** [comment] 2023-11-22 17:15
all of them

**Comment by Ayush-Vish** [comment] 2023-12-15 18:05
@Amanyadav207   Are you still working on this issue  ?  
If not please let me know.

**Comment by Amanyadav207** [comment] 2023-12-17 07:32
No I am not working on it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Aryann15** [comment] 2023-12-25 10:58
HI @raamana since Amanya is not working on this issue, Can I start working on this now?  Please let me know. Thanks!

**Comment by raamana** [comment] 2023-12-26 15:26
never mind - i'm closing this for now.

**Closed as completed by raamana** 2023-12-26 15:26 UTC
